CREATE TABLE CATEGORIAS_PRODUTOS 
( 
    CAT_PROD_ID INTEGER NOT NULL, 
    CAT_PROD_DESCRICAO VARCHAR(30) NOT NULL, 
    CAT_PROD_ATIVO CHAR(1) 
);

ALTER TABLE CATEGORIAS_PRODUTOS 
    ADD CONSTRAINT CATEGORIAS_PRODUTOS_PK PRIMARY KEY ( CAT_PROD_ID );

CREATE TABLE CLI_PROC_PREV 
( 
    PROC_PREV_ID INTEGER NOT NULL, 
    CLIENTES_CLI_ID INTEGER NOT NULL 
);

ALTER TABLE CLI_PROC_PREV 
    ADD CONSTRAINT CLI_PROC_PREV_PK PRIMARY KEY ( PROC_PREV_ID, CLIENTES_CLI_ID );

CREATE TABLE CLIENTES 
( 
    CLI_ID INTEGER NOT NULL, 
    CLI_NOME VARCHAR(90) NOT NULL, 
    CLI_GENERO VARCHAR(20), 
    CLI_DATA_NASCIMENTO DATE, 
    CLI_ATIVO CHAR(1) 
);

ALTER TABLE CLIENTES 
    ADD CONSTRAINT CLIENTES_PK PRIMARY KEY ( CLI_ID );

CREATE TABLE FORNECEDORES 
( 
    FORN_ID INTEGER NOT NULL, 
    FORN_RAZAO_SOCIAL VARCHAR(60), 
    FORN_CNPJ VARCHAR(20), 
    FORN_ATIVO CHAR(1) 
);

ALTER TABLE FORNECEDORES 
    ADD CONSTRAINT FORNECEDORES_PK PRIMARY KEY ( FORN_ID );

CREATE TABLE FORNECEDORES_PRODUTOS 
( 
    FORNECEDORES_FORN_ID INTEGER NOT NULL, 
    PRODUTOS_PROD_ID INTEGER NOT NULL 
);

ALTER TABLE FORNECEDORES_PRODUTOS 
    ADD CONSTRAINT FORNECEDORES_PRODUTOS_PK PRIMARY KEY ( FORNECEDORES_FORN_ID, PRODUTOS_PROD_ID );

CREATE TABLE ITENS 
( 
    ITE_ID INTEGER NOT NULL, 
    ITE_NOME VARCHAR(60), 
    PRODUTOS_PROD_ID INTEGER NOT NULL, 
    ITE_ATIVO CHAR(1), 
    ITE_QUANTIDADE_ATUAL DOUBLE PRECISION, 
    ITE_QUANTIDADE_SAIDA_ALTERADA DOUBLE PRECISION, 
    ITE_LOTE_NOME VARCHAR(60), 
    ITE_LOTE_DATA_AQUISICAO DATE, 
    ITE_LOTE_DATA_VENCIMENTO DATE 
);

ALTER TABLE ITENS 
    ADD CONSTRAINT ITENS_PK PRIMARY KEY ( ITE_ID );

CREATE TABLE ITENS_PROCEDIMENTOS_CONCLUIDOS 
( 
    ITENS_ITE_ID INTEGER NOT NULL, 
    PROC_CONC_ID INTEGER NOT NULL, 
    ITENS_PROC_CONC_QNT_USADA DOUBLE PRECISION 
);

ALTER TABLE ITENS_PROCEDIMENTOS_CONCLUIDOS 
    ADD CONSTRAINT ITENS_PROC_CONC_PK PRIMARY KEY ( ITENS_ITE_ID, PROC_CONC_ID );

CREATE TABLE MEDIDAS 
( 
    MED_ID INTEGER NOT NULL, 
    MED_DESCRICAO VARCHAR(30) NOT NULL, 
    MED_SIGLA VARCHAR(10) NOT NULL, 
    MED_ATIVO CHAR(1) 
);

ALTER TABLE MEDIDAS 
    ADD CONSTRAINT MEDIDA_PK PRIMARY KEY ( MED_ID );

CREATE TABLE PARAMETROS 
( 
    PARAM_COR_4 VARCHAR(10), 
    PARAM_COR_5 VARCHAR(10), 
    PARAM_ID INTEGER NOT NULL, 
    PARAM_RAZAO_SOCIAL VARCHAR(60), 
    PARAM_COR_1 VARCHAR(10), 
    PARAM_COR_2 VARCHAR(10), 
    PARAM_COR_3 VARCHAR(10), 
    PARAM_URL_LOGO VARCHAR(100), 
    PARAM_URL_FAVICON VARCHAR(100) 
);

ALTER TABLE PARAMETROS 
    ADD CONSTRAINT PARAMETROS_PK PRIMARY KEY ( PARAM_ID );

CREATE TABLE PROCEDIMENTOS 
( 
    PROC_ID INTEGER NOT NULL, 
    PROC_NOME VARCHAR(60) NOT NULL, 
    PROC_DESCRICAO VARCHAR(60), 
    PROC_ATIVO CHAR(1) 
);

ALTER TABLE PROCEDIMENTOS 
    ADD CONSTRAINT PROCEDIMENTOS_PK PRIMARY KEY ( PROC_ID );

CREATE TABLE PROCEDIMENTOS_CONCLUIDOS 
( 
    PROC_CONC_ID INTEGER NOT NULL, 
    PROC_CONC_DATA_CONCLUSAO TIMESTAMP NOT NULL, 
    PROC_PREV_ID INTEGER NOT NULL, 
    PROC_CONC_ALTERACAO_PADRAO CHAR(1), 
    USUARIOS_USU_ID INTEGER NOT NULL 
);

CREATE UNIQUE INDEX PROCEDIMENTOS_CONCLUIDOS__IDX ON PROCEDIMENTOS_CONCLUIDOS ( PROC_PREV_ID ASC );

ALTER TABLE PROCEDIMENTOS_CONCLUIDOS 
    ADD CONSTRAINT PROCEDIMENTOS_CONCLUIDOS_PK PRIMARY KEY ( PROC_CONC_ID );

CREATE TABLE PROCEDIMENTOS_PREVISTOS 
( 
    PROC_PREV_ID INTEGER NOT NULL, 
    PROC_PREV_DATA_AGENDADO_PARA TIMESTAMP, 
    PROC_PREV_DATA_AGENDADO_EM TIMESTAMP, 
    PROCEDIMENTOS_PROC_ID INTEGER NOT NULL, 
    PROC_PREV_CANCELADO CHAR(1), 
    USUARIOS_USU_PREV_ID INTEGER NOT NULL, 
    USUARIOS_USU_CANCELOU_ID INTEGER NOT NULL 
);

ALTER TABLE PROCEDIMENTOS_PREVISTOS 
    ADD CONSTRAINT PROCEDIMENTOS_PREVISTOS_PK PRIMARY KEY ( PROC_PREV_ID );

CREATE TABLE PRODUTOS 
( 
    PROD_ID INTEGER NOT NULL, 
    PROD_DESCRICAO VARCHAR(90) NOT NULL, 
    PROD_QUANTIDAE_MINIMA DOUBLE PRECISION, 
    MEDIDAS_MED_ID INTEGER NOT NULL, 
    CAT_PROD_ID INTEGER NOT NULL, 
    CAT_ATIVO CHAR(1) 
);

ALTER TABLE PRODUTOS 
    ADD CONSTRAINT PRODUTOS_PK PRIMARY KEY ( PROD_ID );

CREATE TABLE PRODUTOS_PROCEDIMENTOS 
( 
    PRODUTOS_PROD_ID INTEGER NOT NULL, 
    PROCEDIMENTOS_PROC_ID INTEGER NOT NULL, 
    PROD_PROC_QUANTIDADE_SAIDA DOUBLE PRECISION 
);

ALTER TABLE PRODUTOS_PROCEDIMENTOS 
    ADD CONSTRAINT PRODUTOS_PROCEDIMENTOS_PK PRIMARY KEY ( PRODUTOS_PROD_ID, PROCEDIMENTOS_PROC_ID );

CREATE TABLE PROMOCOES 
( 
    PROM_ID INTEGER NOT NULL, 
    PROM_DATA_MINIMA DATE NOT NULL, 
    PROM_DATA_MAXIMA DATE NOT NULL, 
    PROM_ATIVO CHAR(1) 
);

ALTER TABLE PROMOCOES 
    ADD CONSTRAINT PROMOCOES_PK PRIMARY KEY ( PROM_ID );

CREATE TABLE PROMOCOES_PROCEDIMENTOS 
( 
    PROM_PROC_ID INTEGER NOT NULL, 
    PROCEDIMENTOS_PROC_ID INTEGER NOT NULL, 
    PROMOCOES_PROM_ID INTEGER NOT NULL 
);

ALTER TABLE PROMOCOES_PROCEDIMENTOS 
    ADD CONSTRAINT PROMOCOES_PROCEDIMENTOS_PK PRIMARY KEY ( PROM_PROC_ID );

CREATE TABLE USUARIOS 
( 
    USU_ID INTEGER NOT NULL, 
    USU_NOME VARCHAR(60) NOT NULL, 
    USU_LOGIN VARCHAR(30) NOT NULL, 
    USU_SENHA VARCHAR(60) NOT NULL, 
    USU_E_ADM CHAR(1) NOT NULL, 
    USU_ATIVO CHAR(1) 
);

ALTER TABLE USUARIOS 
    ADD CONSTRAINT USUARIOS_PK PRIMARY KEY ( USU_ID );

ALTER TABLE PRODUTOS 
    ADD CONSTRAINT CATEGORIAS_PRODUTOS_FK FOREIGN KEY ( CAT_PROD_ID ) REFERENCES CATEGORIAS_PRODUTOS ( CAT_PROD_ID );

ALTER TABLE CLI_PROC_PREV 
    ADD CONSTRAINT CLIENTES_FK FOREIGN KEY ( CLIENTES_CLI_ID ) REFERENCES CLIENTES ( CLI_ID );

ALTER TABLE FORNECEDORES_PRODUTOS 
    ADD CONSTRAINT FORNECEDORES_FK FOREIGN KEY ( FORNECEDORES_FORN_ID ) REFERENCES FORNECEDORES ( FORN_ID );

ALTER TABLE ITENS_PROCEDIMENTOS_CONCLUIDOS 
    ADD CONSTRAINT ITENS_FK FOREIGN KEY ( ITENS_ITE_ID ) REFERENCES ITENS ( ITE_ID );

ALTER TABLE ITENS 
    ADD CONSTRAINT ITENS_PRODUTOS_FK FOREIGN KEY ( PRODUTOS_PROD_ID ) REFERENCES PRODUTOS ( PROD_ID );

ALTER TABLE PRODUTOS 
    ADD CONSTRAINT MEDIDAS_FK FOREIGN KEY ( MEDIDAS_MED_ID ) REFERENCES MEDIDAS ( MED_ID );

ALTER TABLE ITENS_PROCEDIMENTOS_CONCLUIDOS 
    ADD CONSTRAINT PROC_CONC_FK FOREIGN KEY ( PROC_CONC_ID ) REFERENCES PROCEDIMENTOS_CONCLUIDOS ( PROC_CONC_ID );

ALTER TABLE PROCEDIMENTOS_PREVISTOS 
    ADD CONSTRAINT PROC_FK FOREIGN KEY ( PROCEDIMENTOS_PROC_ID ) REFERENCES PROCEDIMENTOS ( PROC_ID );

ALTER TABLE CLI_PROC_PREV 
    ADD CONSTRAINT PROC_PREV_FKv3 FOREIGN KEY ( PROC_PREV_ID ) REFERENCES PROCEDIMENTOS_PREVISTOS ( PROC_PREV_ID );

ALTER TABLE PROCEDIMENTOS_CONCLUIDOS 
    ADD CONSTRAINT PROC_PREV_ID FOREIGN KEY ( PROC_PREV_ID ) REFERENCES PROCEDIMENTOS_PREVISTOS ( PROC_PREV_ID );

ALTER TABLE PROCEDIMENTOS_PREVISTOS 
    ADD CONSTRAINT PROCE_PREV_USUARIOS_FK FOREIGN KEY ( USUARIOS_USU_CANCELOU_ID ) REFERENCES USUARIOS ( USU_ID );

ALTER TABLE PRODUTOS_PROCEDIMENTOS 
    ADD CONSTRAINT PROCEDIMENTOS_FK FOREIGN KEY ( PROCEDIMENTOS_PROC_ID ) REFERENCES PROCEDIMENTOS ( PROC_ID );

ALTER TABLE PROMOCOES_PROCEDIMENTOS 
    ADD CONSTRAINT PROCEDIMENTOS_FKv2 FOREIGN KEY ( PROCEDIMENTOS_PROC_ID ) REFERENCES PROCEDIMENTOS ( PROC_ID );

ALTER TABLE FORNECEDORES_PRODUTOS 
    ADD CONSTRAINT PRODUTOS_FK FOREIGN KEY ( PRODUTOS_PROD_ID ) REFERENCES PRODUTOS ( PROD_ID );

ALTER TABLE PRODUTOS_PROCEDIMENTOS 
    ADD CONSTRAINT PRODUTOS_FKv2 FOREIGN KEY ( PRODUTOS_PROD_ID ) REFERENCES PRODUTOS ( PROD_ID );

ALTER TABLE PROMOCOES_PROCEDIMENTOS 
    ADD CONSTRAINT PROMOCOES_FK FOREIGN KEY ( PROMOCOES_PROM_ID ) REFERENCES PROMOCOES ( PROM_ID );

ALTER TABLE PROCEDIMENTOS_PREVISTOS 
    ADD CONSTRAINT USU_FK FOREIGN KEY ( USUARIOS_USU_PREV_ID ) REFERENCES USUARIOS ( USU_ID );

ALTER TABLE PROCEDIMENTOS_CONCLUIDOS 
    ADD CONSTRAINT USU_ID FOREIGN KEY ( USUARIOS_USU_ID ) REFERENCES USUARIOS ( USU_ID );